# Generated by Django 3.1.1 on 2021-01-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
