# Generated by Django 3.1.1 on 2021-01-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools_User', '0002_auto_20210107_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=100, unique=True, verbose_name='用户名'),
        ),
    ]
