# Generated by Django 3.1.1 on 2021-01-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools_User', '0004_auto_20210107_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=200, verbose_name='token'),
        ),
    ]
